# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9e5b4219d13cfad2b86f1369cd545d1a"
name = "PRNTONDEMAND"
application_url = "https://example.com/"
embedded = true
handle = "prntondemand"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_themes,write_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
