# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b9b69a3fa0f318446147ef2dfe89c91"
name = "prntondemand"
application_url = "https://prntondemand-oeiv5hd5z-baljeets-projects-4ac20978.vercel.app"
embedded = true
handle = "prntondemand-3"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,read_themes,write_customers,write_orders,write_products,write_themes"

[auth]
redirect_urls = ["https://prntondemand-oeiv5hd5z-baljeets-projects-4ac20978.vercel.app/auth/callback"]

[pos]
embedded = false
